# Generated by Django 5.0.4 on 2024-04-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('prioridade', models.CharField(max_length=100)),
                ('data_limite', models.DateField(max_length=50)),
                ('descricao', models.CharField(max_length=1000)),
                ('arquivo', models.FileField(upload_to='')),
            ],
        ),
    ]
