# Generated by Django 5.0.4 on 2024-04-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coodernadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('nome_coodernador', models.CharField(max_length=100)),
                ('email_coodernador', models.EmailField(max_length=100)),
            ],
        ),
    ]
