# Generated by Django 5.0.4 on 2024-04-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_coodernadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
