# Generated by Django 5.0.4 on 2024-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_dados_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='acao',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='estagio',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='dados',
            name='status',
            field=models.CharField(default='Pendente', max_length=50),
        ),
        migrations.AddField(
            model_name='dados',
            name='ultima_atualizacao',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
