# Generated by Django 5.0.4 on 2024-05-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_dados_acao_dados_estagio_dados_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='estagio',
            field=models.CharField(default='1/4', max_length=50),
        ),
    ]
