# Generated by Django 5.0.4 on 2024-05-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0005_alter_dados_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='arquivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
