# Generated by Django 5.0.4 on 2024-05-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0006_alter_dados_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='arquivo',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='dados',
            name='estagio',
            field=models.CharField(default='1/5', max_length=50),
        ),
    ]
