# Generated by Django 5.0.4 on 2024-05-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_alter_dados_arquivo_alter_dados_estagio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coodernadores',
            new_name='UsuariosBD',
        ),
        migrations.RenameField(
            model_name='usuariosbd',
            old_name='email_coodernador',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuariosbd',
            old_name='nome_coodernador',
            new_name='nome',
        ),
    ]
