# Generated by Django 5.0.4 on 2024-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0008_rename_coodernadores_usuariosbd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='data_limite',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
