# Generated by Django 5.0.4 on 2024-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0010_usuariosbd_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosbd',
            name='estagio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
