# Generated by Django 5.0.4 on 2024-05-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0011_alter_usuariosbd_estagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
